name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

env:
  SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_SAND_0813E1910 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Use Node.js 20.19.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package build
        run: |
          rm -rf artifact
          mkdir -p artifact
          cp -r dist/EcommerceUI/browser/* artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: swa-build
          path: artifact

  deploy_preview:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && github.base_ref == 'develop'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: swa-build
          path: artifact

      - name: Deploy SWA (Preview)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          skip_app_build: true
          app_location: "artifact"
          output_location: ""
          api_location: ""
          repo_token: ${{ secrets.GITHUB_TOKEN }} # comentarios en el PR

  deploy_prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: swa-build
          path: artifact

      - name: Deploy SWA (Prod)
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          skip_app_build: true
          app_location: "artifact"
          output_location: ""
          api_location: ""
